#!/bin/sh

# Specific values for that build
SRC_SOURCECODE_REPO_NAME=mockIotGpsDeviceAwsSdkV2
DST_SOURCECODE_REPO_NAME=$SRC_SOURCECODE_REPO_NAME
DST_SOURCECODE_REPO_DESC="LaFleet - Emulated IoT GPS Device based on aws-iot-device-sdk-v2"

CODEBUILD_NAME=$DST_SOURCECODE_REPO_NAME
BUILD_DESCRIPTION=$DST_SOURCECODE_REPO_DESC
# Suffix _VALUE is required for one sed in a json
IMAGE_REPO_NAME_VALUE=mock-iot-gps-device-awssdkv2
CODEBUILD_BRANCH_NAME=main


THING_NAME=$DST_SOURCECODE_REPO_NAME
THING_TOPIC=topic_1

CW_IOT_DEVICE_LOGS_LOG_GROUP=/$PROJECT_NAME/iot/$PROJECT_NAME-$THING_NAME-logs
CW_IOT_DEVICE_LOGS_IAM_ROOT=$PROJECT_NAME-iot-cw-write-$THING_NAME-logs
CW_IOT_DEVICE_LOGS_IAM_POLICY_NAME=$CW_IOT_DEVICE_LOGS_IAM_ROOT-policy
CW_IOT_DEVICE_LOGS_IAM_POLICY_ARN=arn:aws:iam::$AWS_ACCOUNT_ID_VALUE:policy$IAM_SERVICE_PATH$CW_IOT_DEVICE_LOGS_IAM_POLICY_NAME
CW_IOT_DEVICE_LOGS_IAM_ROLE_NAME=$CW_IOT_DEVICE_LOGS_IAM_ROOT-role
CW_IOT_DEVICE_LOGS_IAM_ROLE_ARN=arn:aws:iam::$AWS_ACCOUNT_ID_VALUE:role$IAM_SERVICE_PATH$CW_IOT_DEVICE_LOGS_IAM_ROLE_NAME

CW_IOT_DEVICE_ERROR_LOG_GROUP=/$PROJECT_NAME/iot/$PROJECT_NAME-$THING_NAME-error-logs
CW_IOT_DEVICE_ERROR_IAM_ROOT=$PROJECT_NAME-iot-cw-write-$THING_NAME-error-logs
CW_IOT_DEVICE_ERROR_IAM_POLICY_NAME=$CW_IOT_DEVICE_ERROR_IAM_ROOT-policy
CW_IOT_DEVICE_ERROR_IAM_POLICY_ARN=arn:aws:iam::$AWS_ACCOUNT_ID_VALUE:policy$IAM_SERVICE_PATH$CW_IOT_DEVICE_ERROR_IAM_POLICY_NAME
CW_IOT_DEVICE_ERROR_IAM_ROLE_NAME=$CW_IOT_DEVICE_ERROR_IAM_ROOT-role
CW_IOT_DEVICE_ERROR_IAM_ROLE_ARN=arn:aws:iam::$AWS_ACCOUNT_ID_VALUE:role$IAM_SERVICE_PATH$CW_IOT_DEVICE_ERROR_IAM_ROLE_NAME

THING_TXT_FILENAME=certificate-id.txt
THING_CRT_FILENAME=certificate.pem.crt
THING_PUB_FILENAME=public.pem.key
THING_PRV_FILENAME=private.pem.key
THING_RCA_FILENAME=root-ca.crt
