#!/bin/sh

# Specific values for that build
SRC_SOURCECODE_REPO_NAME=redisearchQueryClient
DST_SOURCECODE_REPO_NAME=$SRC_SOURCECODE_REPO_NAME
DST_SOURCECODE_REPO_DESC="LaFleet - Service to query Redisearch in Javascript"

CODEBUILD_NAME=$DST_SOURCECODE_REPO_NAME
BUILD_DESCRIPTION=$DST_SOURCECODE_REPO_DESC
IMAGE_REPO_NAME_VALUE=redisearch-query-client
CODEBUILD_BRANCH_NAME=main
