#!/bin/sh

MAPBOX_TOKEN=$(grep MAPBOX_TOKEN .env.production | cut -d '=' -f2)


# Specific values for that build
SRC_SOURCECODE_REPO_NAME=reactFrontend
DST_SOURCECODE_REPO_NAME=$SRC_SOURCECODE_REPO_NAME
DST_SOURCECODE_REPO_DESC="LaFleet - React Frontend in TypeScript"

CODEBUILD_NAME=$DST_SOURCECODE_REPO_NAME
BUILD_DESCRIPTION=$DST_SOURCECODE_REPO_DESC
IMAGE_REPO_NAME_VALUE=$DST_SOURCECODE_REPO_NAME
CODEBUILD_BRANCH_NAME=main
