#!/bin/sh

# Specific values for that build
SRC_SOURCECODE_REPO_NAME=sqsConsumerToRedisearchJs
DST_SOURCECODE_REPO_NAME=$SRC_SOURCECODE_REPO_NAME
DST_SOURCECODE_REPO_DESC="LaFleet - SQS Consumer to Redisearch in Javascript"

CODEBUILD_NAME=$DST_SOURCECODE_REPO_NAME
BUILD_DESCRIPTION=$DST_SOURCECODE_REPO_DESC
IMAGE_REPO_NAME_VALUE=sqsconsumer-toredisearch-js
CODEBUILD_BRANCH_NAME=main
