apiVersion: apps/v1
kind: Deployment
metadata:
  name: lafleet-devices-slow
  namespace: default
  labels:
    app: devices
    project: lafleet
    speed: slow
spec:
  selector:
    matchLabels:
      app: devices
  replicas: 2
  template:
    metadata:
      name: devices
      labels:
        app: devices
    spec:
      containers:
      - name: mock-iot-gps-device-awsskdv2
        image: <aws_account_id>.dkr.ecr.<aws_region>.amazonaws.com/mock-iot-gps-device-awsskdv2:latest
        env:
        - name: ENDPOINT
          value: "<endpoint>-ats.iot.<aws_region>.amazonaws.com"
        - name: TOPIC
          value: "topic_1"
        - name: INTERVAL
          value: "1000"
        - name: COUNT
          value: "100"
        - name: CA_FILE
          value: "./certs/root-ca.crt"
        - name: CERT_FILE
          value: "./certs/certificate.pem.crt"
        - name: KEY_FILE
          value: "./certs/private.pem.key"
        resources:
          limits:
            memory: "60Mi"
            cpu: "80m"
          requests:
            memory: "30Mi"
            cpu: "40m"
      nodeSelector:
        nodegroup-type: backend-standard