apiVersion: batch/v1
kind: Job
metadata:
  name: lafleet-devices-extreme-job
  namespace: default
  labels:
    app: devices
    project: lafleet
    speed: extreme
spec:
  parallelism: 20
  completions: 20
  template:
    metadata:
      name: devices
      labels:
        app: devices
    spec:
      containers:
      - name: mock-iot-gps-device-awsskdv2
        image: IMAGE_VALUE
        env:
        - name: ENDPOINT
          value: "IOT_ENDPOINT"
        - name: TOPIC
          value: "topic_1"
        - name: INTERVAL
          value: "10"
        - name: COUNT
          value: "15000"
        - name: CA_FILE
          value: "./certs/root-ca.crt"
        - name: CERT_FILE
          value: "./certs/certificate.pem.crt"
        - name: KEY_FILE
          value: "./certs/private.pem.key"
        resources:
          limits:
            memory: "60Mi"
            cpu: "80m"
          requests:
            memory: "30Mi"
            cpu: "40m"
      restartPolicy: "OnFailure"
      nodeSelector:
        nodegroup-type: backend-standard
