#!/bin/sh

LOG_GROUP=$CW_IOT_DEVICE_LOGS_LOG_GROUP
IAM_POLICY_NAME=$CW_IOT_DEVICE_LOGS_IAM_POLICY_NAME
IAM_POLICY_ARN=$CW_IOT_DEVICE_LOGS_IAM_POLICY_ARN
IAM_ROLE_NAME=$CW_IOT_DEVICE_LOGS_IAM_ROLE_NAME
. ./iam/create_cw_logs_device_role.sh
